language: objective-c
env:
  - NODE_VERSION="0.12"
  - NODE_VERSION="4.0"
  - NODE_VERSION="4.1"
  - NODE_VERSION="4.2"
  - NODE_VERSION="5.0"
  - NODE_VERSION="5.1"
  - NODE_VERSION="5.2"
  - NODE_VERSION="5.3"
  - NODE_VERSION="5.4"
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
    source /tmp/.nvm/nvm.sh;
    nvm install $NODE_VERSION;
    nvm use $NODE_VERSION;
install:
  - npm install
script:
  - npm test
deploy:
  - provider: npm
    email: michelboudreau@gmail.com
    api_key:
        secure: nUvKxoOySO2UMM17oU197Yi8fbEWYWx19K/qACTtNp86RVNdEOOgGRzS07CAE6LSBYhLMTWvoKoHDzgm5OVfquChlfhq7wf3P18guIeczDOvBPR8Kp5AufmCCTUMTyIk8tm5BYuAXLtXAiCDxVfDWueG326NrN6L0FOgY0MATrUFO1tJSL9IgIcchG1OzH3oMAUFEeTurefoqoMuJxL3Pn6bLOQRD7jR+03T6mLXNdLi2PxbtS6kTYT2ivuOTAOiiJ+NXyWOxqkWBV3EMCoWCltW2xLENzLfW+58lR+8Bvfco+Wmh/41MpV8IEpVaLISLf/ARvfczHtTFVJ3te2RQUzhGATnKG5r2AZgnZM9r5WEgBeFJEXBJltloz7vSOZV0QS3AP5RZE8z7qlZOhUPYbb4v/Zx+NbZ+SKUZ1wPHHStLdscNocGfO3RxJtCD+C2+STuFVGHTITNLc5K8DYGGRoTbkySnNXnLrCeT9ig1Vh+TCiQQ/jZmEVAESWF5RM7Qx4Dpwkw29P/038uL4yF9J/BpD/JN08e+tyNLsvTQJhJp/O6GFXU4eXmUnwy1u9diQh2hB61adJjfeA6QKihSIpFZzx28+O7TaGBjn7KLqT2yImwFtCzDzhTL/yKAWKP1j3OfYLFTLEqGW4fm5pB8mtKHPYbvaObNnQkAQpn3/k=
    on:
      branch: master
      tags: true
